# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mattias Axell
tagline:             My Learning Journal through Third Year of Exam Project at Kaospilot in Denmark 
url:                 http://mattiasaxell.nu
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mattias Axell
  url:               http://mattiasaxell.com
  email:             hi@mattiasaxell.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Top Header
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
