# Site settings
title: The Learning Journal of Mattias Axell
header-img: img/home-bg.jpg
email: hi@mattiasaxell.com
description: "Follow my Learning Process during my Exam Project at Kaospilot!"
baseurl: ""
url: "http://mattiasaxell.nu"
twitter_username: okfse
github_username:  mattiasaxell
facebook_username:  OpenSweden

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
